### ISSUE TITLE
Update base image to CentOS 7

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#1]
Currently, the base image in use is `centos:7.5` instead of `centos:7`.

This is due to possible problems lurking beyond an update described in IQSS/dataverse#5374.
It might be totally unrelated and just caused by the preparation scripts, but better safe than sorry.

This issue tracks the progress and is used for a switch test. Let's see how this goes.

**Comment by pdurbin** [comment]
This is probably a good idea. I was just reading this article called "Top ten most popular docker images each contain at least 30 vulnerabilities":

https://snyk.io/blog/top-ten-most-popular-docker-images-each-contain-at-least-30-vulnerabilities/

I guess I'm wondering how often the dataverse-k8s image will need to be rebuilt. I assume the base image is being patched frequently by the operating system vendor (Red Hat, in this case).

**Comment by poikilotherm** [comment]
Yes it is :-)

I am thinking about switching from Docker Hub Automated Builds to a proper Travis CI job, as [Travis offers scheduled rebuilds](https://docs.travis-ci.com/user/cron-jobs/). A rebuild of all Docker tags every day or every two days could be a good idea... ;-)

Obviously it would be better to even take this further and let a test-suite run to ensure nothing breaks from a OS/base image change.

**Comment by poikilotherm** [comment]
After testing the image based on `centos:7` nothing blew up - just Exceptions unrelated to the base image.
