### ISSUE TITLE
Adding new user and running the application in Intranet

### ISSUE THREAD

**Issue by mshariful** [IQSS/dataverse-kubernetes#114]
Hello,
I have two questions: 
1)  Is it possible to install dataverse-kubernetes in our Intranet so that few user can use it? Is there any special requirements?
2) Today I  added an user  "TestUser" (using 'Signup'). TestUser got logged in automatically, but s/he could not create or even see any existing dataverse that are created by dataverseAdmin. Is this normal? How can I change this?
Update: I have found out that I can make TestUser also "Super User". Then s/he can see/edit etc. But I would like to give TestUser only limited rights. How do I do that?

Thank you very much for your kind attention.

Best regards,
Shariful

**Comment by poikilotherm** [comment]
Hi @mshariful,

regarding your first question: yes, you can run this for your group in your intranet. You will have to run a Kubernetes environment for this, which might be an issue for your IT department.

Regarding your second question: please consult the [Dataverse guides](http://guides.dataverse.org). This project is just about deployment, usage docs can be found in the user documentation. You can also seek for advice on IRC or in the [Google Group](http://groups.google.com/group/dataverse-community).

I'm going to close this issue now. If you feel your questions have not been answered thouroghly, please leave a comment. :smiley_cat:

**Comment by mshariful** [comment]
Thank you very much for your reply.  I have found out that I can make TestUser also "Super User". Then s/he can see/edit etc. But I would like to give TestUser only limited rights. How do I do that?
