### ISSUE TITLE
How to run on Elastic Container Service for Kubernetes (Amazon EKS)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-kubernetes#12]
@whorka and I were just chatting about how I've used minikube to spin up dataverse-kubernetes but I don't know how to spin it up in the cloud. I have access to EKS. Here are some screenshots:

![screen shot 2019-02-28 at 3 19 28 pm](https://user-images.githubusercontent.com/21006/53595859-5c25d200-3b6c-11e9-93c4-411157344992.png)

![screen shot 2019-02-28 at 3 21 12 pm](https://user-images.githubusercontent.com/21006/53595912-85466280-3b6c-11e9-850d-b530cd59045c.png)

The problem is I don't know what I'm doing in this EKS interface. Can we add some tips to the README so I can try dataverse-kubernetes on EKS? I'm happy to start with either the EKS web interface or the command line. When I spin up Dataverse on EC2 I use our handy `ec2-create-instance.sh` script: http://guides.dataverse.org/en/4.11/developers/deployment.html

**Comment by whorka** [comment]
If it helps, here are the guides I used when setting up EKS using Terraform:

https://learn.hashicorp.com/terraform/aws/eks-intro

https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html

The Hashicorp guide lists all the AWS resources that go into an EKS 
infrastructure, although it doesn't particularly explain how they all 
work together.

The AWS guide explains how the resources work together, but in some 
cases it uses CloudFormation templates that obscure exactly which 
resources are being added, whereas the Hashicorp doc lists them all 
explicitly.

  -Bill

**Comment by pdurbin** [comment]
@whorka thanks! @joelmarkanderson knows Terraform: https://github.com/IQSS/dataverse-aws/issues/11#issuecomment-368989741

These guides are pretty involved. Much more complicated than `vagrant up` or our `
ec2-create-instance.sh` script. 😄 

Some day it would be nice to have step by step instructions from the Dataverse perspective like what I wrote here for EC2: http://guides.dataverse.org/en/4.11/developers/deployment.html

The problem is, learning this stuff and writing step by step instructions takes time. My usual approach is to ask the community to make a pull request, especially if the work doesn't make it into an @IQSS sprint.

**Comment by whorka** [comment]
On 2/28/19 6:24 PM, Philip Durbin wrote:
> 
> These guides are pretty involved. Much more complicated than |vagrant 
> up| or our |ec2-create-instance.sh| script. 😄

Sure, but the output of that process is a .tf file that you apply with 
`terraform apply`. What you're seeing there are the nuts and bolts.

> Some day it would be nice to have step by step instructions from the 
> Dataverse perspective like what I wrote here for EC2: 

That looks a lot like the documentation I wrote for our Operations group 
about how to apply the Terraform manifest to AWS.

Granted, there are a few extra steps -- like configuring your AWS API 
credentials and joining the Kubernetes worker nodes to the cluster -- 
which happen outside of Terraform.

It's still a work in progress and customized for our environment, but if 
you like I can also send you those artifacts as they stand today.

  -Bill

**Comment by pdurbin** [comment]
@whorka sure! Please do send me those artifacts! Thanks!

**Comment by pdurbin** [comment]
@donsizemore and I chatted about this at http://irclog.iq.harvard.edu/dataverse/2019-03-06#i_87776 and he said he'd take a look. Thanks!

**Comment by donsizemore** [comment]
I'm getting my feet wet via microk8s and minikube. Reported some snags to @poikilotherm and we'll try again. Haven't forgotten about testing in EKS.

**Comment by pdurbin** [comment]
@poikilotherm hi! As discussed at http://irclog.iq.harvard.edu/dataverse/2019-04-24#i_91580 I just emailed AWS credentials to you. You have the same access as me and @donsizemore 

If there's anything I can do to help (such as provide some of the artifacts mentioned above), please let me know! Thanks!!

**Comment by poikilotherm** [comment]
I just tested to use `kops` to deploy a minimal K8s cluster on EC2 and deploy Dataverse to it.
Will try EKS later... :wink: 

Feel free to test and give me some feedback. :smile:

**Comment by pdurbin** [comment]
@poikilotherm I just **read** https://github.com/IQSS/dataverse-kubernetes/blob/aab28ac2cd1248adfee6652daba45438c145fb76/docs/aws-kops.md at least. Seems cool. Thanks!

**Comment by poikilotherm** [comment]
Beware: I used `kops` to deploy the cluster and did not use EKS.

I looked into EKS during the last hour and it seems to be a lot more work than running this stuff on your own... At least for a demo using `kops` had been a lot quicker.

Didn't try oout `terraform` yet.

**Comment by poikilotherm** [comment]
As @pdurbin responded [on IRC today](http://irclog.iq.harvard.edu/dataverse/2019-05-16#i_93827), I am going to close this issue.

#45 has been merged into master and should reflect at least how to use this on AWS with a custom cluster. At this point in time, I wouldn't recommend running this on AWS EKS.

Please feel free to raise a new issue if you have any questions left or new information. Feel free to try things out! Any feedback is appreciated.
