### ISSUE TITLE
how to install with docker-compose

### ISSUE THREAD

**Issue by benzaked** [IQSS/dataverse-kubernetes#125]
Hi, I need help with a guide or some tips on how to install this repo without any use of Kubernetes
Tnx!

**Comment by 4tikhonov** [comment]
Hi @benzaked, you can try http://github.com/IQSS/dataverse-docker, it's just simple docker-compose infrastructure.

**Comment by benzaked** [comment]
hi, @4tikhonov tnx for the fast replay. I tried it earlier and I get GlassFish index.html every time I go to 
http://localhost:8085 instead of dataverse login page.

**Comment by 4tikhonov** [comment]
Weird, as far as I know it was installed in a few places last week. I'll take a look.

**Comment by poikilotherm** [comment]
Closing in favor of #118

**Comment by pdurbin** [comment]
@benzaked in addition to #118 you could take a look at https://github.com/IQSS/dataverse/blob/v4.17/conf/docker-dcm/readme.md . I don't think I ever ran the docker-compose file myself but my colleague did when working on adding S3 support to the Data Capture Module (DCM). Should work. For dev. :smile:

**Comment by benzaked** [comment]
Thank you @4tikhonov and all. @4tikhonov I will love for an update If you succeed.
