### ISSUE TITLE
Add simple Apache Reverse Proxy with mod_auth_mellon

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#14]
To easily test SAML authentication for Dataverse, a simple image, based on mod_auth_mellon should be created. That is because Shibboleth is much more complex than needed for this simple demo showcase.

It might even be relevant for simple production instances reusing a institution-only SAML IdP instead of a full grown federation like eduGain and the like.

Configuration of the Apache (and thus also the SP) should be easily done from a `ConfigMap`.
The image should be based on an official Apache image like https://hub.docker.com/_/httpd

Sample configuration should be done against https://samltest.id so it is usefull for a demo showcase.

**Comment by pdurbin** [comment]
I first heard about mod_auth_mellon at NorthEast Linux Fest (NELF) 2014 and talked about it around 6:00 at https://soundcloud.com/philipdurbin/dataverse-on-hacker-public-radio-1490

In the end, I went with mod_shib. Here are the latest docs: http://guides.dataverse.org/en/4.11/installation/shibboleth.html

In 2016 someone added about mod_auth_mellon support at https://help.hmdc.harvard.edu/Ticket/Display.html?id=232112 but they stopped responding.

I like it when people have options so please let me know if I can help.

**Comment by poikilotherm** [comment]
Starting work on this in https://github.com/IQSS/dataverse-kubernetes/tree/14-samldemo
