### ISSUE TITLE
Making pod with namespace but validation error appearing,what to do now?

### ISSUE THREAD

**Issue by azeem2412** [IQSS/dataverse-kubernetes#191]
error: error validating "myfirstpod1.yaml": error validating data: [ValidationError(Pod.spec.containers[0].ports[0]): unknown field "conatainerPort" in io.k8s.api.core.v1.ContainerPort, ValidationError(Pod.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort]; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by poikilotherm** [comment]
Hi @azeem2412, could you please ellaborate on what you are trying to do?

It looks like you are trying to do sth. with a custom pod specification, which does not seem very related to this project. Have you taken a [look at the guide](https://dataverse-k8s.rtfd.io)?

**Comment by poikilotherm** [comment]
This is something completely unrelated. Closing.
