### ISSUE TITLE
Define RAM limits/guarantees in K8s

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#21]
The deployment descriptors should contain a reasonable limitations and guarantees for computing resources.

See https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/

**Comment by poikilotherm** [comment]
This is an absolute necessity for #63, as the Payara image is using a JVM with container support and no other limits set to gain maximum momentum out of the containers resources.

Without limitation, the JVM will believe it is free to eat all of your RAM. Beware.

**Comment by poikilotherm** [comment]
We need to take a look at minimizing the amount of RAM configured, so it will be sufficient to run a `minikube` VM with 4 GB RAM. Using 2 GB for the Dataverse container will result in problems for redeployment. If less than 2 GB is not sufficient, we need to create a dev persona, where we use the recreate strategy (as we do for Solr due to locking issues).

**Comment by pdurbin** [comment]
Last I looked the free tier for OpenShift Online limits you to 1 GB of memory. It would be nice if someday Dataverse could slim down to fit into those jeans. 👖 😄 🍔

**Comment by poikilotherm** [comment]
Dataverse fits into 1 GiB, but uses at least 512 MiB. See new guide :wink: 
Together with Solr and Postgres I don't think this can be squezzed into such a very small plan.
Using minikube with 4096 MB RAM seems to sufficient :smile: 

I won't add CPU limits for now.
