### ISSUE TITLE
Handle in Dataverse Image

### ISSUE THREAD

**Issue by alsantiagoabreu** [IQSS/dataverse-kubernetes#217]
Hello guys,

I have some doubts about how to install Handle in the dataverse image.
I'm using payara flavor and I can put Handle in the image, however I have to run some asadmin and CURL commands using docker exec.... My doubt is how can I run these comands ? In which file can I write the commands to be executed during the dataverse image built? Asadmin requires user/password... Can I automate this part even with user/password requirement to run asadmin?

PS.: From this project, I'm using only the dataverse image.

**Comment by Kris-LIBIS** [comment]
I doubt that you can run asadmin commands when building images. You may have to schedule them at boot time by adding a script to ${SCRIPT_DIR} or ${SCRIPT_DIR}/init.d. See https://blog.payara.fish/flexibility-first-payara-docker-images-allow-a-completely-custom-start-up-configuration for more information.

**Comment by poikilotherm** [comment]
Hi @alsantiagoabreu,

I'm not sure what you are trying to do when "installing Handle in the dataverse image". Is this only about configuration of Dataverse software? Or is there some daemon you need to run in parallel, too?

In general, please familiarize with the usual Dockerfile to run commands during build. Anything else can happen as init scripts, please take a look at the upstream Payara image to see how this works (`init_2_.....sh` is using this to run some setup before Payara starts) as @Kris-LIBIS already pointed out. (Didn't knew about this blog post, although I commited the initial work on this... :smile: )

Please be aware that I really try to move to Dataverse 5, move the image generation to the upstream project etc. I would also like to [create an operator](https://github.com/gdcc/dvopa), which might automate some more tasks if necessary.

**Comment by Kris-LIBIS** [comment]
@poikilotherm FYI, we currently have version 5.3 running in a Docker swarm and used this repository as a sample. I had some issues, but not too much.

**Comment by poikilotherm** [comment]
Off topic 1: @Kris-LIBIS you're most welcome to create a PR against the docs to add this flavor of running things in the cloud. I try not to emphasize to much on K8s, although I have the impression of Swarm being a dead product. (Long live the dead...)

Off topic 2: good to know you're not experiencing to much hassles. On one of the next Community Calls I'm going to speak about Microprofile Config and what's in it for devs and ops. Maybe you wanna join.

**Comment by alsantiagoabreu** [comment]
Thank you guys =D
