### ISSUE TITLE
Connecting to a PSQL server outside dataverse server

### ISSUE THREAD

**Issue by alsantiagoabreu** [IQSS/dataverse-kubernetes#219]
Hello guys.

Our postgres server is outside the server where we have dataverse container.
From the dataverse container I can run psql -h OUR_PSQL_SERVER -U user base -p port and it works. However when I put these information in configuration files it doesn't work. Moreover, if I try to edit config/domain.xml  it also doesn't work. In another image of dataver we have both way described works, however that image doesn't use payara....
Can you help me please ?
Thanks in advance, best regards!
Alexandre

**Comment by poikilotherm** [comment]
Simply override the env variables found in 

https://github.com/gdcc/dataverse-kubernetes/blob/413cd89cc51ce4768dea831f0eb3280da60635f8/docker/dataverse-k8s/bin/default.config#L3-L6

Please be aware that this will become easier when I release the Dataverse 5.3+ images (currently in progress), as I introduced MicroProfile Config Support for the database connection.

**Comment by alsantiagoabreu** [comment]
Hi @poikilotherm , I've changed it in default.config too, but it isn't worked too =/

**Comment by poikilotherm** [comment]
Please consult the docs about a convenient way to change an env var in your K8s deployment.
http://k8s-docs.gdcc.io/en/v4.20/day1/config.html

Sorry - with only limited information about your environment, your deployment routines and your inherited images, I'm not able to help you here. Just too many moving parts.

Please reach out on IRC for further discussion, as this is an issue tracker, not a support forum. Thank you!
(I'm going to close this issue now)
