### ISSUE TITLE
Add scheduled image builds for improved security

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#22]
Images should be updated regularly when the base image (currently CentOS) is updated.

Linked builds on Docker Hub only work for non-official images (they might have a lack of resources...), so we need to add this ourselfs.

First idea: use Travis CI, they offer scheduled builds OOB.

**Comment by pdurbin** [comment]
You might want to investigate using https://jenkins.dataverse.org which is a new resource that will be documented in https://github.com/IQSS/dataverse/issues/5725

If you'd like some jobs to be added, I would suggest opening issues at https://github.com/IQSS/dataverse-jenkins/issues

**Comment by poikilotherm** [comment]
This should include a regular security scan when building the images.

This can be done using Clair as standalone, Anchore or similar. See also [blog post on different engines part 1](https://kubedex.com/container-scanning/) and [part 2](https://kubedex.com/follow-up-container-scanning-comparison/).
