### ISSUE TITLE
validation errors during kubectl apply

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse-kubernetes#56]
opening by @poikilotherm's request. trying today with minikube and kubectl 1.14 on Ubuntu 18.04, i see:

`error: error validating "k8s/utils/postgresql/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

`error: error validating "k8s/solr/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

`error: error validating "k8s/dataverse/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`

I did choose to ignore the errors, and am waiting on Dataverse to initialize.

**Comment by poikilotherm** [comment]
This error message is due to the nature of `kubectl` reading all YAML files it sees in the directory. As long as you are not used `kubectl apply -k` (which activates Kustomize), validation will fail.

See also kubernetes-sigs/kustomize#738, which describes pretty well, that adding `apiVersion` and `kind` has not yet been sorted out.

@donsizemore do you think I should rework all docs to use Kustomize, so this warnings go away?

**Comment by azeem2412** [comment]
error: error validating "myfirstpod1.yaml": error validating data: [ValidationError(Pod.spec.containers[0].ports[0]): unknown field "conatainerPort" in io.k8s.api.core.v1.ContainerPort, ValidationError(Pod.spec.containers[0].ports[0]): missing required field "containerPort" in io.k8s.api.core.v1.ContainerPort]; if you choose to ignore these errors, turn validation off with --validate=false

making pod with namespace this error appearing again n again? please guide

**Comment by poikilotherm** [comment]
Hi @azeem2412 this issue is closed. Your comment does not seem related to the original issue and you opened another issue #191 about the same. Please keep the conversation there. Thank you!

**Comment by ghost** [comment]
Guys i had this error and i didn't know how to fix it
YamlValidationException: Failed to validate 'data\nlu.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in data\nlu.yml:502:
      Key 'synonyme' was not defined. Path: '/nlu/45'
  in data\nlu.yml:502:
      Value 'b'- d\\xe9p\\xf4t fixe\\n'' is not a list. Value path: '/nlu/45/examples'
  in data\nlu.yml:506:
      Key 'synonyme' was not defined. Path: '/nlu/46'
  in data\nlu.yml:506:
      Value 'b'- d\\xe9p\\xf4t r\\xe9current\\n'' is not a list. Value path: '/nlu/46/examples'

**Comment by ghost** [comment]
This is my nlu file

version: "2.0"

nlu:

- intent: welcome  
  examples: |
   - Content de vous revoir
   - Bienvenue

- intent: greet
  examples: |
   - Salut 
   - Bonjour
   - salut
   - bonjour
   - Bonsoir

- intent: goodbye
  examples: | 
   - au revoir
   - Au revoir
   - à plus tard
   - Bye Bye
   - à plus
   - Bonne nuit 
   - bonne nuit
   - à plus tard
   - Au revoir
   - J'ai fini
   - Bonne journée
   - arrêter
   - BYEE
   - AU REVOIR
   - Merci beaucoup. A plus
   - Passe une bonne journée. il est temps de partir, au revoir

- intent: affirm
  examples: |
   - Oui
   - D'accord 
   - bien sûr
   - Ç'est vrai 
   - correctement
   - Ouais
   - oui
   - ouais
   - Je suis bon
   - Je suis d'accord
   - exactement
   - Oui, s'il vous plaît
   - oui, je le ferais
   - c'est exact
   - sûr
   - Oui, merci.
   - Surement 

- intent: refuse
  examples: |
   - non
   - jamais
   - Je ne pense pas
   - je n'aime pas ça
   - certainement non
   - pas vraiment
   - Non
   - non merci
   - non ce n'est pa le cas
   - pas celui-là
   - n'utilisez pas cela
   - s'il vous plaît non
   - Non, ne faites pas ça.

- intent: inform
  examples: |
   - demain
   - la semaine prochaine
   - hier
   - pour aujourd'hui
   - La semaine dernière
   - le mois dernier
   - les deux derniers jours
   - les deux dernières semaines
   - Je voudrais payer [current balance](amount-of-money)
   - [current balance](amount-of-money)
   - [full](amount-of-money)
   - Le [full balance](amount-of-money)
   - [minimum balance](amount-of-money)
   - Je voudrais payer [minimum balance](amount-of-money)
   - [current balance](amount-of-money)
   - [minimum balance](amount-of-money)
   - Le [minimum balance](amount-of-money)
   - Mon [current balance](amount-of-money)
   - Tout mes [cards](account_type)
  
- intent: branch_locator
  examples: |
   - pouvez-vous me parler des succursales près de moi?
   - à quelle distance se trouve la succursale la plus proche?
   - combien et où sont les succursales de votre banque?
   - dites-moi la succursale la plus proche !
   - où est la succursale de votre banque?
   - localiser une succursale à proximité

- intent: atm_locator
  examples: |
   - pouvez-vous me parler des guichets automatiques près de chez moi?
   - à quelle distance se trouve le guichet automatique le plus proche?
   - combien et où sont les guichets automatiques de votre banque?
   - Donnez-moi le guichet automatique le plus proche
   - où est le guichet automatique de votre banque?
   - localiser un guichet automatique à proximité

- intent: types_of_ loans
  examples: | 
   - quels sont les différents types de prêts?
   - combien de types de prêts existe-t-il?
   - parlez-moi des prêts que vous proposez ?
   - quels sont les types de prêt ?


- intent: loan_home_about
  examples: | 
   - parlez-moi des prêts bancaires à l'habitat
   - qu'est-ce qu'un prêt au logement ?

- intent: home_loan_rate
  examples: |
   - quel est le taux d'intérêt pour un prêt au logement ?
   - indiquez-moi le taux d'intérêt pour le prêt au logement
   - à combien s'élève le taux d'intérêt du prêt au logement ?

- intent: documents_of_loan_to_the_home_required
  examples: | 
   - quels sont les documents requis pour un prêt au logement ?
   - quels sont les documents requis pour le prêt au logement ?
   - quels sont les documents requis pour un prêt au logement ?

- intent: loan_time_to_home_required
  examples: |
   - indiquez-moi la durée du processus de prêt au logement
   - quelle est la durée de la procédure pour un prêt au logement ?
   - quel est le délai nécessaire pour un prêt au logement ?

- intent: loan_period
  examples: | 
   - quelle est la durée du prêt au logement ?
   - Quelle est la durée du prêt au logement ?

- intent: loan_home_max_amount
  examples: | 
   - quel est le montant maximum pour le prêt au logement ?
   - indiquez-moi le montant maximum pour le prêt au logement
   - quel est le montant maximum du prêt au logement ?

- intent: loan_home_min_amount
  examples: | 
   - indiquez-moi le montant minimum pour le prêt au logement
   - quel est le montant minimum pour un prêt au logement ?

- intent: Personal_loan
  examples: | 
   - parlez-moi des prêts bancaires personnels
   - qu'est-ce qu'un prêt personnel ?

- intent: interest_rate_personal_loan
  examples: |
   - quel est le taux d'intérêt pour un prêt personnel ?
   - indiquez-moi le taux d'intérêt pour un prêt personnel
   - à combien s'élève le taux d'intérêt pour un prêt personnel ?

- intent: personal_documents_required_loan
  examples: | 
   - quels sont les documents requis pour un prêt personnel ?
   - quels sont les documents demandés pour un prêt personnel ?
   - Quels sont les documents requis pour un prêt personnel ?

- intent: period_of_personal_loan
  examples: |
   - indiquez-moi la durée du processus de prêt personnel
   - quelle est la durée de la procédure pour un prêt personnel ?
   - quel est le délai nécessaire pour un prêt personnel ?


- intent: personal_loan_amount_max
  examples: |
   - quel est le montant maximum du prêt personnel ?
   - indiquez-moi le montant maximum du prêt personnel
   - quel est le montant maximum d'un prêt personnel ?

- intent: personal_loan_amount_min
  examples: |
   - quel est le montant minimum pour un prêt personnel ?
   - indiquez-moi le montant minimum pour un prêt personnel
   - Quel est le montant minimum pour un prêt personnel ?

- intent: account_types
  examples: |
   - pouvez-vous me parler des différents types de comptes bancaires ?
   - quels sont les différents types de comptes bancaires ?
   - combien y a-t-il de types de comptes bancaires ?

- intent: savings_account_about
  examples: |
   - parlez-moi du compte d'épargne
   - qu'est-ce qu'un compte d'épargne ?

- intent: saving_account_advantages
  examples: |
   - à quoi sert un compte d'épargne ?
   - quels sont les avantages du compte d'épargne ?
   - Quels sont les avantages du compte d'épargne ?

- intent: saving_account_disadvantages
  examples: |
   - à quoi sert un compte d'épargne ?
   - quels sont les inconvénients des comptes d'épargne ?
   - quels sont les inconvénients du compte d'épargne ?

- intent: current_account_about
  examples: | 
   - parlez-moi de compte bancaire courant
   - qu'est-ce qu'un compte courant ?

- intent: current_account_advantages
  examples: |
   - à quoi sert le compte courant ?
   - quels sont les avantages de la balance des opérations courantes ?
   - quels sont les avantages du compte courant ?

- intent: current_account_disadvantages
  examples: |
   - à quoi sert le compte courant ?
   - quels sont les inconvénients du compte courant ?
   - Quels sont les inconvénients du compte courant ?

- intent: account_dr_about
  examples: |
   - parlez-moi du compte bancaire de dépôt récurrent
   - qu'est-ce qu'un compte bancaire de dépôt récurrent ?

- intent: account_df_about
  examples: |
   - parlez-moi du compte bancaire à dépôt fixe
   - qu'est-ce qu'un compte bancaire à dépôt fixe ?

- intent: card_types
  examples: |
   - Parlez-moi des types de cartes disponibles
   - quels sont les types de cartes ?
   - combien y a-t-il de cartes ?

- intent: card_loan_about
  examples: |
   - qu'est-ce qu'une carte de crédit ?
   - parlez-moi d'une carte de crédit

- intent: card_loan_types
  examples: |
   - Parlez-moi des types de cartes de crédit disponibles
   - quels sont les types de cartes de crédit ?
   - combien y a-t-il de cartes de crédit ?

- intent: card_debit_about
  examples: |
   - qu'est-ce qu'une carte de débit ?
   - parlez-moi d'une carte de débit

- intent: card_debit_types
  examples: |
   - Parlez-moi des types de cartes de débit disponibles
   - quels sont les types de cartes de débit ?
   - combien y a-t-il de cartes de débit ?

- intent: internet_banking_about
  examples: |
   - qu'est-ce que la banque sur internet ?
   - parlez-moi de la banque sur internet
   - qu'est ce que c'est STBNet?
   - pallez-moi de stbnet

- intent: check_balance
  examples: |
   - Combien d'argent y a-t-il dans mon compte?
   - Combien d'argent y a-t-il dans mon compte [bank] (account_type)?
   - quel est mon [balance] (amount-of-money)?
   - quel est mon [current-balance] (amount-of-money)?
   - Que reste-t-il sur ce compte?
   - Combien ai-je sur ce compte?
   - Quel est le [balance] (amount-of-money) sur ce compte?
   - Combien d'argent reste-t-il sur ce compte?
   - Quelle est ma [carte de crédit] (account_type) [balance] (montant-d'argent)
   - What's my [credit](account_type) [balance](amount-of-money)
   - Combien d'argents j'ai sur [credit cards](account_type)
   - Montre moi ma [credit card](account_type) [balance](amount-of-money)
   - Montrez moi [credit](account_type) comptes
   - Quelle est la [balance](amount-of-money) on my [credit](account_type) compte
   - Quel est mon [credit](account_type) compte
   - What's my [emblem](credit_card) [card](account_type) [balance](amount-of-money)
   - Montre moi mon [bank](credit_card) [balance](amount-of-money)
   - What's my [justice bank](credit_card) [balance](amount-of-money)
   - Quelle est ma [balance](amount-of-money) dans le [bank](credit_card) compte
   - Quel est mon [credit card](account_type) [balance](amount-of-money)?
   - quel est mon [credit card](account_type) account [balance](amount-of-money)?
   - Combien d'argent ai-je dépensé ?
   - Je devrais vérifier mon [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money) [first](account_type)
   - vérifier mon [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money)
   - Verifier mon [credit card]{"entity": "account_type", "value": "credit"} [balance](amount-of-money) [first](account_type)
   - Pouvez-vous m'informer sur  mon compte [balance](amount-of-money)?
   - Bonjour, j'aimerais savoir combien d'argent il y a dans mon compte
   - Salut, quel est le solde de mon compte s'il vous plaît
   - Alors quel est mon [balance](amount-of-money)?
   - Quel est mon [current balance](amount-of-money)
   - Quel est mon [balance](amount-of-money)?
   - Combien d'argent ai-je?
   - Dans quels endroits ai-je dépensé de l'argent?
   - Attends, je vais d'abord devoir vérifier mon solde. Pouvez-vous me faire ça s'il vous plait?
   - Salut, j'ai besoin de savoir combien d'argent il y a dans mon [checking](account_type) compte

- intent: check_earnings
  examples: |
   - Combien d'argent ai-je gagné l'année dernière?
   - Qu'est-ce que j'ai gagné le mois dernier?
   - Combien ai-je gagné le mois dernier?
   - Combien d'argent ai-je gagné la semaine dernière?
   - combien a été déposé sur mon compte le mois dernier?
   - combien a été déposé sur mon compte au cours des deux dernières semaines?
   - vérifier les dépôts de la semaine dernière
   - total des dépôts sur l'année dernière
   - combien a été déposé en janvier
   - combien d'argent ai-je gagné?
   - qu'est-ce que j'ai gagné?
   - Combien ai-je gagné?

- intent: pay_credit_card
  examples: |
    - Je veut payer le  [minimum balance](amount-of-money) sur mon (credit_card) [card](account_type)
    - Je voudrais payer le [credit card](account_type)
    - Je paye [card](account_type)
    - Payer mon [card](account_type)
    - Je voudrais payer [credit card](account_type) facture
    - Je veux payer [current balance](amount-of-money) sur mon [credit card](account_type)
    - Pouvez-vous m'aider à payer le [current balance](amount-of-money) sur mon [credit card](account_type)
    - i want to pay off my [credit card](account_type)
    - I want to pay off my [credit card](account_type)
    - i want to pay my [credit card](account_type)
    - i want to pay off my [emblem](credit_card) [credit card](account_type)
    - I want to pay my [current balance](amount-of-money) on my [embelm](credit_card) [credit card](account_type)
    - i want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type)
    - I want to pay $500 on my [emblem](credit_card) [credit card](account_type) on Sunday
    - I want to pay my [current balance](amount-of-money) on my [emblem](credit_card) [credit card](account_type) today
    - i need to pay off my [emblm](credit_card) [credit card](account_type)
    - Please schedule  a payment towards my [credit card](account_type) for April 12th
    - Can I schedule a payment towards my [credit card](account_type) for tomorrow?
    - Pay off my [minimum balance](amount-of-money) please
    - i would like to pay $1200 to my [credit card]{"entity": "account_type", "value": "credit"}
    - I would also like to pay my [visa](credit_card) bill
    - Pay off my [credit card]{"entity": "account_type", "value": "credit"}, please
    - I guess it is. Since it's so much, let's pay off my [credit](account_type)
    - Let's pay that [credit card]{"entity": "account_type", "value": "credit"} bill
    - I want to pay 100 dollars toward my [Emblem](credit_card) [card](account_type), tomorrow
    - pay 100 towards [emblem](credit_card) [card](account_type), tomorrow
    - Je veux payer ma facture
    - could I pay off my [credit card]{"entity": "account_type", "value": "credit"}?
    - pay off my [credit card]{"entity": "account_type", "value": "credit"}
    - i wanna pay my [credit card]{"entity": "account_type", "value": "credit"}
    - Payez ma facture !

- intent: search_transactions
  examples: |
    - combien ai-je dépensé chez [Target] (vendor_name) cette semaine?
    - Quelles sont mes dépenses habituelles chez [Amazon] (vendor_name)?
    - Je veux vérifier mon historique de dépenses
    - combien ai-je dépensé chez [Starbucks] (vendor_name) la semaine dernière?
    - J'ai besoin de vérifier mon historique de dépenses
    - Je veux vérifier mes dépenses
    - Je souhaite consulter l'historique de mes dépenses
    - je veux vérifier mon historique de dépenses
    - je veux voir l'historique de mes transactions
    - Je souhaite rechercher mes transactions passées
    - puis-je rechercher l'historique de mes transactions
    - puis-je consulter les transactions passées
    - Je souhaite rechercher mes transactions avec [amazon] (vendor_name)
    - puis-je consulter mes transactions avec [target] (vendor_name)
    - combien ai-je dépensé chez [starbucks] (vendor_name) le mois dernier?
    - qu'est-ce que j'ai dépensé le mois dernier?
    - Combien ai-je dépensé le mois dernier?
    - Qu'ai-je dépensé à [Legoland] (vendor_name) le mois dernier?
    - Qu'ai-je dépensé à [Legoland] (vendor_name) l'année dernière?
    - combien ai-je dépensé chez [starbucks] (vendor_name) l'année dernière
    - Oui! Combien ai-je dépensé pour [Starbucks] (vendor_name) le mois dernier?
    - Combien ai-je dépensé chez Burger King le mois dernier?
    - dans quels endroits ai-je dépensé de l'argent?
    - Qu'ai-je dépensé chez [Starbucks] (vendor_name) en mai?
    - Combien d'argent ai-je perdu contre [starbucks] (vendor_name) en mai?
    - Combien ai-je réellement dépensé chez [target] (vendor_name) le mois dernier? J'adorerais savoir.
    - Pouvez-vous me dire combien j'ai dépensé chez [Ikea] (vendor_name) ce mois-ci?
    - Pouvez-vous me dire combien j'ai dépensé dans les coffeeshops ce mois-ci?
    - Pouvez-vous me dire combien j'ai dépensé en café ce mois-ci?
    - Qu'ai-je dépensé chez [Costco] (vendor_name) le mois dernier?
    - qu'ai-je dépensé à [target] (vendor_name) le mois dernier
    - où ai-je dépensé le plus d'argent le mois dernier?

- intent: thankyou
  examples: |
   - Merci, au revoir
   - ok merci au revoir
   - Merci bye
   - euh bien merci au revoir
   - Merci
   - et c'est tout merci et au revoir
   - d'accord, merci
   - Merci
   - Merci au revoir
   - Merci et au revoir
   - Merci!
   - Génial, tu es un bon robot!

- intent: transfer_money
  examples: |
    - Je voudrais payer [Amen](PERSON)
    - Je veut transferer la somme d'argent à [Ahmed](PERSON)
    - can i transfer money to [Sally](PERSON)
    - Je veux transférer de l'argent
    - Je veux payer quelqu'un
    - puis-je payer quelqu'un
    - J'ai besoin de transférer de l'argent à un ami
    - puis-je transférer de l'argent à mon [quelqu'un] (PERSONNE)
    - Je veux payer [Bert] (PERSONNE)
    - paie mon ami
    - Transférer de l'argent
    - Je souhaite transférer 150 dinars à [Hamza] (PERSONNE)
    - Je souhaite transférer 300 dinars à [Mohamed] (PERSONNE)
    - Je veux payer [Paula Handy] (PERSONNE)
    - payez 40 $ à Ali s'il vous plaît
    - transférer 60 $ à [Salah Salih] (PERSONNE)
    - payer [Evan Oslo] (PERSONNE)
    - payez [Lisa] (PERSONNE) s'il vous plaît
    - Puis-je transférer de l'argent à [Kyle Gardner] (PERSONNE)?
    - Payer [Karen] (PERSONNE) 60 Euros
    - payer [Mona] (PERSONNE) 60 $
    - transférer 60 $ à [Sally] (PERSONNE)
    - besoin de transférer de l'argent
    - Je veux transférer à [Kelly] (PERSONNE)
    - Payer [Percy] (PERSONNE) 50 $
    - Payez 50 $ à [Pat] (PERSONNE)
    - Ok paye [Emma] (PERSONNE)
    - payer [Emanual] (PERSONNE)
    - Je voulais transferer une somme à [personne] (PERSONNE)
    - Je souhaite transférer 100 $ à ma [fille] (PERSONNE)
    - je veux transférer de l'argent s'il vous plaît
    - je veux dire, je veux transférer de l'argent
    - J'ai besoin de payer une personne.
    - transférer de l'argent à [ethan oswald] (PERSONNE)
    - transférer de l'argent à [sara] (PERSONNE)
    - J'ai besoin de transférer de l'argent à ma grand-mère [Judith] (PERSONNE).
    - Je souhaite transférer de l'argent vers [Latisha] (PERSONNE)
    - J'ai besoin de faire un transfert urgent à [Bob] (PERSONNE), pouvez-vous le faire?
    - Ahh, d'accord alors je veux faire un transfert à [Bob] (PERSONNE).
    - Puis-je transférer de l'argent à un ami?
    - J'ai besoin de transférer de l'argent à [Jeff] (PERSONNE), mon fils
    - J'ai besoin d'envoyer de l'argent à mon enfant
    - J'ai besoin de transférer de l'argent
    - envoyer 50 $ à [john jacob] (PERSONNE)
    - J'ai besoin de transférer de l'argent à mon collègue qui a payé le déjeuner
    - Salut j'aime envoyer de l'argent
    - Je souhaite envoyer 50 $ à [John] (PERSONNE)
    - Bonjour, j'aime envoyer de l'argent à [John] (PERSONNE)
    - Veuillez transférer 50 dollars à [Andreas] (PERSONNE)
    - Je souhaite transférer de l'argent à [Philipp] (PERSONNE)
    - Je souhaite transférer 50 $ à [Joschka] (PERSONNE)

- intent: check_recipients
  examples: |
   - À qui puis-je envoyer de l'argent?
   - Qui sont mes destinataires connus
   - Montrez-moi ma liste de destinataires
   - Afficher la liste des destinataires
   - Montrez-moi les personnes auxquelles je peux envoyer de l'argent
   - Qui est un bénéficiaire valide
   - qui puis-je payer?
   - qui puis-je transférer de l'argent?
   - qui est dans ma liste de destinataires?
   - À qui puis-je transférer de l'argent?
   - qui est dans ma liste de destinataires connus?
   - Pouvons-nous recommencer?
   - À qui puis-je transférer de l'argent?
   - À qui puis-je transférer de l'argent?
   - D'accord. À qui puis-je transférer de l'argent alors?
   - puis-je voir la liste des destinataires connus?

- intent: help
  examples: |
   - Que pouvez-vous faire?
   - que puis-je vous demander?
   - avec quoi pouvez-vous m'aider?
   - aide-moi
   - comment utiliser ceci
   - comment pouvez vous m'aider
   - Que pouvez-vous faire?
   - J'ai besion de l'aide?

- synonyme: df
  examples: |
   - dépôt fixe

- synonyme: dr
  examples: |
   - dépôt récurrent

- synonym: credit
  examples: |
    - credit card
    - credit cards
    - credit account
    - credit accounts
    - card
    - cards
    - credit card account

- synonym: current balance
  examples: |
    - balance
    - full
    - full balance
