### ISSUE TITLE
Deployment to Minikube fails with weird errors

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#57]
@donsizemore and @wilkos-dans experienced issues when deploying Dataverse 4.14 to Minikube.

No real or helpfull errors were logged (except the normal exceptions about Rserve password alias and code scanning), the DAS just went away.

I could reproduce this with default Minikube config CPU=2, MEM=2048 on KVM2 driver. This seems to be memory related, as my API server had been killed, too.

After using CPU=2, MEM=4096 I could successfully deploy, but now I experience issues with the bootstrapping script.

Dataverse is really memory hungry:
```
> kubectl top pod -A | sort -h -k4
NAMESPACE     NAME                               CPU(cores)   MEMORY(bytes)   
kube-system   kube-addon-manager-minikube        14m          5Mi             
kube-system   coredns-fb8b8dccf-pztgf            18m          8Mi             
kube-system   coredns-fb8b8dccf-wsx8f            16m          9Mi             
kube-system   kube-proxy-xhtbh                   5m           12Mi            
kube-system   kube-scheduler-minikube            8m           12Mi            
kube-system   storage-provisioner                1m           14Mi            
kube-system   heapster-64b4q                     1m           19Mi            
kube-system   influxdb-grafana-xcf5c             12m          40Mi            
kube-system   kube-controller-manager-minikube   95m          41Mi            
kube-system   etcd-minikube                      99m          44Mi            
default       postgresql-668dccf4cd-pzq5n        12m          51Mi            
kube-system   kube-apiserver-minikube            145m         186Mi           
default       solr-6ddd95c86d-plm8f              5m           227Mi           
default       dataverse-799cd744fd-sfmdl         16m          996Mi           

> kubectl top node                
NAME       CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
minikube   805m         26%    2817Mi          77%
```

**Comment by donsizemore** [comment]
@poikilotherm I tried again with 8192M of RAM with the same results. I wouldn’t run a production Dataverse instance in fewer than 24G of RAM, but my test box isn’t that beefy =(

**Comment by wilkos-dans** [comment]
@poikilotherm I also tried again with minikube start --memory 9200 --cpus 5. This did work, however still some issue's in the dataverse log. Will look into them later. Dataverse-eu has a running instance on GoogleCloud: 13Gb and 2 vCPU's. Thanks.

**Comment by poikilotherm** [comment]
This should be solved now. Added some info to the docs. You will still have problems due to #60...
