### ISSUE TITLE
Create a release schema

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#6]
To make image releases independent from Dataverse releases, a new schema needs to be implemented.

It needs to carry a release info for the image and should contain the Dataverse release used inside the image.

The docker tags need to reflect this - tagged images are not updated by default in Kubernetes, this is only done for "latest" or untagged.

**Comment by pdurbin** [comment]
I googled for "Kubernetes schema" but I'm not sure what this issue is about. Can you please explain a little more, @poikilotherm ? Thanks!

**Comment by poikilotherm** [comment]
I think I will just stick to Dataverse upstream release numbering.

That number is used for image tags, too. Updates to tagged images, e. g. for security purposes, are released under the same tag.

Tagged images are by default image pull policy not updated on the local K8s cluster. This might be changed later when needed.
