### ISSUE TITLE
Bootstrapping fails on Minikube

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#60]
When trying to Bootstrap on Minikube using `kubectl apply -f k8s/dataverse/jobs/bootstrap.yaml`, the `pqsl` call fails with "wrong password".

Need to investigate if this is only happening when using Minikube, etc. This hasn't been touched in a while and is all of a sudden broken...

**Comment by donsizemore** [comment]
I hit this in Minikube 1.1.0 running Kubernetes 1.14.2 on Ubuntu 18.04. The only output of a "kubectl log" for each replica is

`psql: FATAL:  password authentication failed for user "dataverse"`

**Comment by poikilotherm** [comment]
Thx for reporting :smile: At least this is reproducible then. I will try to investigate if this happens with K8s v1.13, too, which had been the one in use when I developed this.

**Comment by poikilotherm** [comment]
I just tried the [demo with k3d](../blob/master/docs/k3s.md) and that worked flawless once I had sufficient diskspace (pruned images and volumes...).

**Comment by poikilotherm** [comment]
Ok I tracked down why this is failing. The job container is run as `root`, not as user `glassfish`. `psql` searches for the `.pgpass` file in `~`, which is (obviously) different for `root` and `glassfish`. As the password cannot be found then, the `psql` command fails, which fails bootstrapping.

Need to investigate why this container is ran as `root` when using Minikube. :unamused:

**Comment by poikilotherm** [comment]
I just opened kubernetes/minikube#4369 and hope for a reply and solution.

**Comment by poikilotherm** [comment]
Alright, this is "solved". All Minikube users @donsizemore and @wilkos-dans, please take a look at the enhanced docs in 526296d
