### ISSUE TITLE
Support loading custom metadata blocks

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse-kubernetes#85]
We need to support people having their own custom metadata blocks. [See upstream docs on this.](http://guides.dataverse.org/en/4.16/admin/metadatacustomization.html#)

1. We need to provide a maintenance job to load TSV based metadata blocks
   * Also needed for changes happening upstream, like for [v4.16 (citation block changed, see point 5 of upgrade instruction)](https://github.com/IQSS/dataverse/releases/tag/v4.16)
2. We need a job exporting the (so called) "dynamic) schema, adding it to the Solr instance and reload. (see also [upstream docs](http://guides.dataverse.org/en/4.16/admin/metadatacustomization.html#updating-the-solr-schema))

**Comment by pdurbin** [comment]
I would love to use dataverse-kubernetes to spin up Dataverse with the custom metadata block included in https://github.com/IQSS/dataverse/issues/6289 by @doigl

**Comment by pdurbin** [comment]
This was implemented today in https://github.com/IQSS/dataverse-ansible/pull/135 for dataverse-ansible and I put some screenshots from my testing in a comment at https://github.com/IQSS/dataverse-ansible/issues/133#issuecomment-555227955

@poikilotherm thanks for `updateSchemaMDB.sh`!

**Comment by 4tikhonov** [comment]
Great! We're going to test it as well!

**Comment by pdurbin** [comment]
@4tikhonov perfect! Thanks!

@donsizemore I just gave you and @poikilotherm a shout out in this thread called "custom metadata blocks now easier to spin up and evaluate" - https://groups.google.com/d/msg/dataverse-community/uKretKox_io/4FyPVAMYBgAJ

Thanks again! 🎉 🎉 🎉
