### ISSUE TITLE
Support CentOS 8

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse-kubernetes#96]
See also https://github.com/IQSS/dataverse-ansible/pull/115

**Comment by poikilotherm** [comment]
Forgive me @pdurbin but wouldn't it make more sense to talk about using Postgres 10 or newer?

Currently, dataverse-k8s Docker image is using CentOS 7, but as we continue with IQSS/dataverse#6230, this will hopefully not be a hard dependency anymore. It should be possible to use different base images (as I already do with the Payara images in #63)

**Comment by donsizemore** [comment]
@poikilotherm I opened an issue asking IQSS to bless PG10+, and it’s on my list today to run the API test suite under 10 and 11.

**Comment by poikilotherm** [comment]
Yeah I saw IQSS/dataverse#6231. Sounds great. It would be very easy to switch to PG10/11/... in K8s, because all you need to do is change the image tag. Can be done manually, via Kustomization, etc.

**Comment by pdurbin** [comment]
@poikilotherm thanks, I wasn't sure how much CentOS 7 is being used in this repo. If it's just dataverse-k8s (`FROM centos:7` in https://github.com/IQSS/dataverse-kubernetes/blob/v4.15.1/docker/dataverse-k8s/Dockerfile#L7 ) does it make sense to close this issue in favor of #63?

**Comment by poikilotherm** [comment]
Maybe you can rename the issue to "Support experimenting with Postgres 10"? In #63, I add an experiments folder and we can create one for Postgres 10, too.

**Comment by pdurbin** [comment]
Meh, I think I'm good. I'll close this and just keep an eye on dataverse-k8s. I'm sure eventually `FROM centos:7` will be replaces with a different `FROM`, maybe an app server image. Thanks. 😄

**Comment by poikilotherm** [comment]
Sure, go ahead :smiley_cat:
